/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshoestore.stockitems;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import projectshoestore.DbUtil;

/**
 *
 * @author saroj_000
 */
public class stockAlert extends javax.swing.JInternalFrame {

    /**
     * Creates new form stockAlert
     */
    public stockAlert() {
        initComponents();
        stockitems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sTable = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("list of prouct getting low");

        sTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.N", "Name", "Address", "Contact no", "Brand"
            }
        ));
        jScrollPane1.setViewportView(sTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sTable;
    // End of variables declaration//GEN-END:variables

    private void stockitems() {
      String st;
      int count=0;
      DefaultTableModel tableModel =(DefaultTableModel) sTable.getModel();
            tableModel.setRowCount(0);
           
        try {
            String sql= "SELECT * FROM hamroshoestore.productinfo;";
            PreparedStatement psd;
            psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs =psd.executeQuery();
            while(rs.next()){
                if(rs.getInt("stock")<=10){
                    System.out.println("1");
                    String brand = rs.getString("brand");
         try {   
             System.out.println(brand);
           String sq= "SELECT * FROM hamroshoestore.supplierinfo where brand ='"+brand+"';";
            PreparedStatement ps;
            ps = DbUtil.getConnection().prepareStatement(sq);
            ResultSet rs1 =ps.executeQuery();
            while(rs1.next()){
            tableModel.addRow(new Object[]{count+1,rs1.getString("name"),rs1.getString("Address"),rs1.getString("contactno"),rs1.getString("brand")});    
            }
                    
                   // st=+"/n";
          }catch (SQLException ex1) {
            Logger.getLogger(stockAlert.class.getName()).log(Level.SEVERE, null, ex1);
        }
        
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(stockAlert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
