/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshoestore.billing;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import projectshoestore.DbUtil;


/**
 *
 * @author saroj_000
 */
public class billingcal extends javax.swing.JFrame {

      @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form billingcal
     */
    public billingcal() {
        initComponents();
        insertionparams();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        billnoTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        billtxt = new javax.swing.JLabel();
        userTxt = new javax.swing.JLabel();
        tenderbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        returnamountBox = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Bill no :");

        jLabel1.setText("Bill Amount       :");

        billnoTxt.setText("jLabel8");

        jLabel2.setText("Tender Amount :");

        jLabel3.setText("Teller :");

        userTxt.setText("jLabel6");

        tenderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenderboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Change Amount :");

        jLabel5.setText("Bill Tender");

        jButton1.setText("bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(returnamountBox, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(billtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tenderbox)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(billnoTxt)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(userTxt)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addComponent(billtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tenderbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(returnamountBox, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(billnoTxt)
                    .addComponent(jLabel3)
                    .addComponent(userTxt))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenderboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenderboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        float abc;
        Float ab,sum,totalprice;
        String cal;
        totalprice = Float.parseFloat(billtxt.getText());
        cal =tenderbox.getText();
        ab =Float.parseFloat(cal);
        sum=ab-totalprice;
        System.out.println(sum);
        returnamountBox.setText(""+sum);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Integer sn=0;
        String st,ft,at,bt,ct,dt,et,gt,ht,it,rate,qty,amount,txt,cashier;
        String billno,username,date,totalam,tenderam,changeam,brand,quantity,prdid,soldprice,ss ;
        date="";
        ss="";
        billno = billnoTxt.getText();
        username=userTxt.getText();
        totalam =billtxt.getText();
        tenderam=tenderbox.getText();
        changeam =returnamountBox.getText();
        
        try {
            String sql = "SELECT * FROM hamroshoestore.tests where billno='"+billno+"';";
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            while(rs.next()){
                sn=sn+1;
                brand=rs.getString("brand");
                quantity=rs.getString("quantity");
                soldprice =rs.getString("soldtotal");
                prdid =rs.getString("productid");
                date=rs.getString("saledate");
                ss=ss+sn+"    "+brand+"("+prdid+")"+"    "+quantity+"       " + soldprice+"\n";
            }
        } catch (SQLException ex) {
            Logger.getLogger(billingcal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        st= "       Hamro Shoes Store";
        st = st+"\n     Chabahil,Kathmandu \n    ABBEVTATED TAX INVOICE";
        st = st+"\n bill no :"+billno+"            Date :"+date;
        
        
        st=st+"\n---------------------------------------------";
        
        at = "\n sn  particulars    Qty    Amount";
        bt = "\n              -----------------------------";
        ct = "\n              Net Amount : "+totalam;
        dt = "\n              -----------------------------";
        et = "\n              Tender :"+tenderam;
        gt = "\n              Change :"+changeam;  
        ft = "\n------------------------------------------";
        
        txt="Serve you with a Smile (PH:01-47818800\nExchange within & Days with invoice \n Open 16 hours)";
        cashier="Cashier :"+username;
        Document doc =new Document();
        try {
            PdfWriter.getInstance(doc,new FileOutputStream("Report.pdf"));
            doc.open();
            doc.add(new Paragraph(st));
            doc.add(new Paragraph(ft));
            doc.add(new Paragraph(at));
            doc.add(new Paragraph(ss));
            
            doc.add(new Paragraph(bt));
            doc.add(new Paragraph(ct));
            doc.add(new Paragraph(dt));
            doc.add(new Paragraph(et));
            doc.add(new Paragraph(gt));
            doc.add(new Paragraph(txt));
            doc.add(new Paragraph(cashier));
            //doc.add(new Paragraph(ht));
            doc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(billingcal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(billingcal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\saroj_000\\Documents\\NetBeansProjects\\New Folder (2)\\project\\Report.pdf");
        } catch (IOException ex) {
            Logger.getLogger(billingcal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        new billingcal().setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingcal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                JFrame jf=new JFrame();
                jf.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                jf.dispose();
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingcal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billnoTxt;
    private javax.swing.JLabel billtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel returnamountBox;
    private javax.swing.JTextField tenderbox;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables

    private void insertionparams() {
        String mm1,a,cal; 
        mm1 = "";
         Integer billno;
         float ab,totalprice,sum,abc;
         
         totalprice=0;
         billno = 0;
       //adding user
        try {
                String sql = "SELECT * FROM hamroshoestore.activeuser;";
                PreparedStatement psd;
                psd = DbUtil.getConnection().prepareStatement(sql);
                ResultSet rs =psd.executeQuery();
            while(rs.next()){
               mm1=rs.getString("Username");
            }
        } catch (SQLException ex) {
            Logger.getLogger(billCalculation1.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(mm1);
        userTxt.setText(mm1);
        
        //adding bill no
        try {
            String sql ="SELECT billno FROM hamroshoestore.billinfo;";
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs;
            rs = psd.executeQuery();
            while(rs.next()){
                
            billno = rs.getInt("billno");
                
                
        }
            
        } catch (SQLException ex) {
            Logger.getLogger(billCalculation1.class.getName()).log(Level.SEVERE, null, ex);
        }
      
           
           a= ""+billno; 
           billnoTxt.setText(a);
           
           try {
            String sql = "SELECT * FROM hamroshoestore.tests where billno='"+billno+"';";
            PreparedStatement psd =DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            while(rs.next()){
                totalprice=totalprice+(rs.getFloat("soldtotal")*rs.getInt("quantity"));
            }
        
        
        } catch (SQLException ex) {
            Logger.getLogger(billCalculation1.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(totalprice);
        billtxt.setText(""+totalprice); 
        
      
            
            
    
    
    
    }
}
