/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshoestore.userregister;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projectshoestore.DbUtil;

/**
 *
 * @author saroj_000
 */
public class Registrationframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form registrationframe
     */
    public Registrationframe() {
        initComponents();
        itemsCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTxtbox = new javax.swing.JTextField();
        nameTxtbox = new javax.swing.JTextField();
        passwordTxtbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userCatcombobox = new javax.swing.JComboBox<>();
        registerBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        jLabel1.setText("Name");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        usernameTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtboxActionPerformed(evt);
            }
        });

        nameTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtboxActionPerformed(evt);
            }
        });

        passwordTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Catagory");

        userCatcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCatcomboboxActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registerBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(userCatcombobox, 0, 116, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(passwordTxtbox))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameTxtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(usernameTxtbox)))))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userCatcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtboxActionPerformed

    private void nameTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtboxActionPerformed

    private void passwordTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtboxActionPerformed

    private void userCatcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCatcomboboxActionPerformed
        String name = userCatcombobox.getSelectedItem().toString();
                 try {
             String sql = "SELECT * FROM hamroshoestore.usercat;";
             String catName;
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            while(rs.next()){
                catName = rs.getString("UserCatagory");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrationframe.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
        
    }//GEN-LAST:event_userCatcomboboxActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        try {
            String name,uName,password,catagory;
            catagory = userCatcombobox.getSelectedItem().toString();
            String sql = "SELECT UserId FROM hamroshoestore.usercat where UserCatagory='"+catagory+"';";
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            int id = 0;
            while(rs.next()){
                id = rs.getInt("UserId");
            }
            name =nameTxtbox.getText();
            uName=usernameTxtbox.getText();
            password= passwordTxtbox.getText();
           
            String sq = "INSERT INTO `hamroshoestore`.`userinfo` ( `name`, `username`, `password`, `catagory`) VALUES ('"+name+"', '"+uName+"', '"+password+"', '"+id+"');";
            Statement ps = DbUtil.getConnection().prepareStatement(sq);
            ps.executeUpdate(sq);
            
        } catch (SQLException ex) {
            Logger.getLogger(Registrationframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        nameTxtbox.setText("");
        usernameTxtbox.setText("");
        passwordTxtbox.setText("");
        this.dispose();
        //JOptionPane.showMessageDialog(null,"register sucessfully");
        
        
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTxtbox;
    private javax.swing.JTextField passwordTxtbox;
    private javax.swing.JButton registerBtn;
    private javax.swing.JComboBox<String> userCatcombobox;
    private javax.swing.JTextField usernameTxtbox;
    // End of variables declaration//GEN-END:variables

    private void itemsCombobox() {
         try {
             String sql = "SELECT * FROM hamroshoestore.usercat;";
             String catName;
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            while(rs.next()){
                catName = rs.getString("UserCatagory");
                userCatcombobox.addItem(catName);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registrationframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
}
