/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshoestore.mainMenu;

import java.awt.Desktop;
import java.awt.GridBagLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import projectshoestore.DbUtil;
import projectshoestore.LoginPage;

import projectshoestore.userregister.Registrationframe;
import projectshoestore.producttinfo.productmain;
import projectshoestore.rEportAndbillpdf.rEportAndBillPdf;
import projectshoestore.stockitems.stockAlert;
import projectshoestore.supplierinfo.supplieractivity;
import projectshoestore.userregister.DeleteUser;

/**
 *
 * @author saroj_000
 */
public class MainMenuAdmin1 extends javax.swing.JFrame {
    

    /**
     * Creates new form MainMenu1
     */
    public MainMenuAdmin1() {
        initComponents();
        stockcount();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        FrameMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        saleMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        adduserMenu = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        userSignoutBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FileMenu.add(jMenuItem1);

        jMenuBar1.add(FileMenu);

        FrameMenu.setText("Menu");
        FrameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrameMenuActionPerformed(evt);
            }
        });

        jMenuItem2.setText("product");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        FrameMenu.add(jMenuItem2);

        jMenuItem3.setText("About supplier");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        FrameMenu.add(jMenuItem3);

        saleMenu.setText("Sales");
        saleMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleMenuActionPerformed(evt);
            }
        });
        FrameMenu.add(saleMenu);

        jMenuBar1.add(FrameMenu);

        jMenu1.setText("User");

        jMenu3.setText("users");

        adduserMenu.setText("Add user");
        adduserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserMenuActionPerformed(evt);
            }
        });
        jMenu3.add(adduserMenu);

        jMenuItem4.setText("Delete user");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        userSignoutBtn.setText("Sign out");
        userSignoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignoutBtnActionPerformed(evt);
            }
        });
        jMenu1.add(userSignoutBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Developer");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrameMenuActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_FrameMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "DELETE FROM `hamroshoestore`.`activeuser` WHERE `id`='1';";
            Statement psd;
            psd = DbUtil.getConnection().createStatement();
            psd.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuAdmin1.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        productmain pp = new productmain(); 
        desktop.add(pp);
        pp.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void userSignoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignoutBtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM `hamroshoestore`.`activeuser` WHERE `id`='1';";
            Statement psd = DbUtil.getConnection().createStatement();
            psd.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuCashier.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        LoginPage lg = new LoginPage();
        lg.setVisible(true);
    }//GEN-LAST:event_userSignoutBtnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     supplieractivity sa = new supplieractivity();
     desktop.add(sa);
     sa.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileMenuActionPerformed

    private void adduserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserMenuActionPerformed
        // TODO add your handling code here:
        JPanel panel1 = new JPanel();
        JPanel panel = new JPanel();
        JPanel panel2 = new JPanel();
        int check =0;
        JLabel label1 = new JLabel("enter a name:");
        JLabel label = new JLabel("Enter a password:");
        JTextField user = new JTextField(10);
        JPasswordField pass = new JPasswordField(10);
        panel.add(panel1.add(label1));
        panel.add(panel1.add(user));
        panel.add(panel2.add(label));
        panel.add(panel2.add(pass));

        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Check",
            JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
            null, options, options[1]);
        if(option == 0) // pressing OK button
        {
            String user1 = user.getText();
            char[] passw = pass.getPassword();
            
            String password = passw.toString();
            System.out.println(passw);
            System.out.println(user1);
            
            try {
                String sql = "SELECT * FROM hamroshoestore.activeuser where Username='"+user1+"';";
                PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
                ResultSet rs = psd.executeQuery();
                while(rs.next()){
                    check=1;
                }
            } catch (SQLException ex) {
                Logger.getLogger(MainMenuAdmin1.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(check);
        if(check==1){
        Registrationframe rf = new Registrationframe();
        desktop.add(rf);
        rf.setVisible(true);
        }
        else JOptionPane.showMessageDialog(null,"Incorrect Username");
        }   
    }//GEN-LAST:event_adduserMenuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        DeleteUser du = new DeleteUser();
        desktop.add(du);
        du.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void saleMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleMenuActionPerformed
        // TODO add your handling code here:
        rEportAndBillPdf rb = new rEportAndBillPdf();
        desktop.add(rb);
        rb.setVisible(true);
    }//GEN-LAST:event_saleMenuActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         String message = "\"Developed By\"\n"
        + "Matish Shrestha\n"+ "Rubin Shrestha\n"+ "Sahil Maharjan\n"+ "Saroj Dangol\n"+"for any error please contact the developer by refering the manual given to you";
    JOptionPane.showMessageDialog(new JFrame(), message, "Dialog",
        JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuAdmin1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu FrameMenu;
    private javax.swing.JMenuItem adduserMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem saleMenu;
    private javax.swing.JMenuItem userSignoutBtn;
    // End of variables declaration//GEN-END:variables

    private void stockcount() {
            stockAlert stt = new stockAlert();
        desktop.add(stt);
        stt.setVisible(true);
            
    }
}
