/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshoestore.producttinfo;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import projectshoestore.DbUtil;
import projectshoestore.doa;
import projectshoestore.dto;

/**
 *
 * @author saroj_000
 */
public class productmain extends javax.swing.JInternalFrame {
    
    
    /**
     * Creates new form productmain
     */
    public productmain() {
        initComponents();
        brandInsert();
        classInsert();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productpanel = new javax.swing.JTabbedPane();
        productsearchpanel = new javax.swing.JPanel();
        ShowallBtn1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        Ptables = new javax.swing.JTable();
        sProductComboBox = new javax.swing.JComboBox<>();
        nameTxtBox = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ProductNameTxtBoxi = new javax.swing.JTextField();
        PriceTxtBoxi = new javax.swing.JTextField();
        QuantityTxtBoxi = new javax.swing.JTextField();
        productUdateBtn = new javax.swing.JButton();
        ShowallBtni = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ProductIdBoxi = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        catComboBoxi = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        brandComboBoxi = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ptableu = new javax.swing.JTable();
        InsertionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProductIdTxtbox = new javax.swing.JTextField();
        ProductnameTxtbox = new javax.swing.JTextField();
        PriceTxtbox = new javax.swing.JTextField();
        QuantityTxtBox = new javax.swing.JTextField();
        InsertBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ptablei = new javax.swing.JTable();
        ShowdataBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        brandComboBox = new javax.swing.JComboBox<>();
        catComboBox = new javax.swing.JComboBox<>();
        productdeletepanel = new javax.swing.JPanel();
        ShowallBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DeleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ProductIdBoxd = new javax.swing.JTextField();
        RefreshBtn = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Ptabled = new javax.swing.JTable();

        setClosable(true);

        ShowallBtn1.setText("Show all data");
        ShowallBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowallBtn1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Search by");

        Ptables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productid", "ProductName", "Brand", "Price", "Quantity", "catagory"
            }
        ));
        jScrollPane6.setViewportView(Ptables);

        sProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Brand" }));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productsearchpanelLayout = new javax.swing.GroupLayout(productsearchpanel);
        productsearchpanel.setLayout(productsearchpanelLayout);
        productsearchpanelLayout.setHorizontalGroup(
            productsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(productsearchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addGap(81, 81, 81))
            .addGroup(productsearchpanelLayout.createSequentialGroup()
                .addGroup(productsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productsearchpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ShowallBtn1))
                    .addGroup(productsearchpanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(sProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(searchBtn)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(productsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(productsearchpanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6)
                    .addContainerGap()))
        );
        productsearchpanelLayout.setVerticalGroup(
            productsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsearchpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShowallBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(productsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
            .addGroup(productsearchpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(productsearchpanelLayout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        productpanel.addTab("Search", productsearchpanel);

        jLabel11.setText("Product Name");

        jLabel12.setText("Product Brand");

        jLabel13.setText("price");

        jLabel14.setText("Quantity");

        ProductNameTxtBoxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameTxtBoxiActionPerformed(evt);
            }
        });

        QuantityTxtBoxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTxtBoxiActionPerformed(evt);
            }
        });

        productUdateBtn.setText("Update");
        productUdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUdateBtnActionPerformed(evt);
            }
        });

        ShowallBtni.setText("Show all Data");
        ShowallBtni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowallBtniActionPerformed(evt);
            }
        });

        jLabel15.setText("Enter the product ID where u wanna make  change and insert new information of current data");

        jLabel16.setText("please fill up all the information");

        catComboBoxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catComboBoxiActionPerformed(evt);
            }
        });

        jLabel18.setText("catagory");

        brandComboBoxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandComboBoxiActionPerformed(evt);
            }
        });

        Ptableu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productid", "ProductName", "Brand", "Price", "Quantity", "catagory"
            }
        ));
        jScrollPane4.setViewportView(Ptableu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(PriceTxtBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(brandComboBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QuantityTxtBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(catComboBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(productUdateBtn)
                                        .addGap(34, 34, 34))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ProductIdBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ShowallBtni)
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11)
                            .addComponent(ProductNameTxtBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ShowallBtni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ProductIdBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameTxtBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceTxtBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandComboBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantityTxtBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catComboBoxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productUdateBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        productpanel.addTab("Update", jPanel3);

        jLabel1.setText("Productid");

        jLabel2.setText("Name");

        jLabel3.setText("Brand");

        jLabel4.setText("PRice");

        jLabel5.setText("Quantity");

        ProductIdTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIdTxtboxActionPerformed(evt);
            }
        });

        ProductnameTxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductnameTxtboxActionPerformed(evt);
            }
        });

        QuantityTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTxtBoxActionPerformed(evt);
            }
        });

        InsertBtn.setText("Insert");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });

        Ptablei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productid", "ProductName", "Brand", "Price", "Quantity", "catagory"
            }
        ));
        jScrollPane2.setViewportView(Ptablei);

        ShowdataBtn.setText("Show all");
        ShowdataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowdataBtnActionPerformed(evt);
            }
        });

        jLabel17.setText("catogory");

        brandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertionPanelLayout = new javax.swing.GroupLayout(InsertionPanel);
        InsertionPanel.setLayout(InsertionPanelLayout);
        InsertionPanelLayout.setHorizontalGroup(
            InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertionPanelLayout.createSequentialGroup()
                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InsertionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(InsertionPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(InsertBtn))
                        .addGap(25, 25, 25)
                        .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InsertionPanelLayout.createSequentialGroup()
                                .addComponent(ShowdataBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(InsertionPanelLayout.createSequentialGroup()
                                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(brandComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProductIdTxtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(27, 27, 27)
                                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProductnameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(catComboBox, 0, 111, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InsertionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PriceTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InsertionPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(QuantityTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        InsertionPanelLayout.setVerticalGroup(
            InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertionPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ProductIdTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ProductnameTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(PriceTxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(brandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(catComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(QuantityTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(InsertionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBtn)
                    .addComponent(ShowdataBtn))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        productpanel.addTab("Insert", InsertionPanel);

        ShowallBtn.setText("Show all");
        ShowallBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowallBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter the Product Id of item which you want to delete");

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Product ID");

        ProductIdBoxd.setText(" ");
        ProductIdBoxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIdBoxdActionPerformed(evt);
            }
        });

        RefreshBtn.setText("Referesh");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        Ptabled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productid", "ProductName", "Brand", "Price", "Quantity", "catagory"
            }
        ));
        jScrollPane5.setViewportView(Ptabled);

        javax.swing.GroupLayout productdeletepanelLayout = new javax.swing.GroupLayout(productdeletepanel);
        productdeletepanel.setLayout(productdeletepanelLayout);
        productdeletepanelLayout.setHorizontalGroup(
            productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(productdeletepanelLayout.createSequentialGroup()
                .addGroup(productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productdeletepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ShowallBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RefreshBtn))
                    .addGroup(productdeletepanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productdeletepanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(28, 28, 28)
                                .addComponent(ProductIdBoxd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productdeletepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteBtn)
                .addGap(86, 86, 86))
            .addGroup(productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(productdeletepanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        productdeletepanelLayout.setVerticalGroup(
            productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productdeletepanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowallBtn)
                    .addComponent(RefreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn)
                    .addComponent(jLabel7)
                    .addComponent(ProductIdBoxd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(600, Short.MAX_VALUE))
            .addGroup(productdeletepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(productdeletepanelLayout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        productpanel.addTab("Delete", productdeletepanel);

        getContentPane().add(productpanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowdataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowdataBtnActionPerformed
        // TODO add your handling code here:
        show_table();
    }//GEN-LAST:event_ShowdataBtnActionPerformed

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        // TODO add your handling code here:
        int idd=0;
        String id,price,stock;
        String name,brand,catagory;
        id = ProductIdTxtbox.getText();
        price = PriceTxtbox.getText();
        stock = QuantityTxtBox.getText();
        name = ProductnameTxtbox.getText();
        brand = brandComboBox.getSelectedItem().toString();
        catagory=catComboBox.getSelectedItem().toString();
       
        
        try {
            String sql ="SELECT id FROM hamroshoestore.productclass where productclass='"+catagory+"';";
            PreparedStatement psd =DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs =psd.executeQuery();
            while(rs.next()){
               idd=rs.getInt("id");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        try {
            String sql ="INSERT INTO `hamroshoestore`.`productinfo` (`ProductID`, `Productname`, `Brand`, `Price`, `Stock`, `productclassid`) VALUES ('"+id+"', '"+name+"', '"+brand+"', '"+price+"', '"+stock+"','"+idd+"');";
            Statement psd = DbUtil.getConnection().createStatement();
            psd.executeUpdate(sql);
            // this.dispose();
        } catch (Exception ex) {ex.printStackTrace();

            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_InsertBtnActionPerformed

    private void QuantityTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTxtBoxActionPerformed

    private void ProductnameTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductnameTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductnameTxtboxActionPerformed

    private void ProductIdTxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIdTxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIdTxtboxActionPerformed

    private void ShowallBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowallBtnActionPerformed
        // TODO add your handling code here:
       // show_tabled();

    }//GEN-LAST:event_ShowallBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        String id = ProductIdBoxd.getText();

        String sql = "DELETE FROM `hamroshoestore`.`productinfo` WHERE `ProductID`='"+id+"';";
        try {
            Statement psd = DbUtil.getConnection().createStatement();
            psd.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ProductIdBoxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIdBoxdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIdBoxdActionPerformed

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
        // TODO add your handling code here:
      show_table();
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void ProductNameTxtBoxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameTxtBoxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameTxtBoxiActionPerformed

    private void QuantityTxtBoxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTxtBoxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTxtBoxiActionPerformed

    private void productUdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUdateBtnActionPerformed
        // TODO add your handling code here:
        int count =0;
        String id,price,stock,name,brand,catagory;
        int idd =0;
        id = ProductIdBoxi.getText();
        price = PriceTxtBoxi.getText();
        stock = QuantityTxtBoxi.getText();
        name = ProductNameTxtBoxi.getText();
        brand = brandComboBoxi.getSelectedItem().toString();
        catagory= catComboBoxi.getSelectedItem().toString();
        try {
            String sql ="SELECT id FROM hamroshoestore.productclass where productclass='"+catagory+"';";
            PreparedStatement psd =DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs =psd.executeQuery();
            while(rs.next()){
               idd=rs.getInt("id");
               count = count+1;
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(count);
        

        try {
            String sql ="UPDATE `hamroshoestore`.`productinfo` SET `Productname`='"+name+"', `Brand`='"+brand+"', `Price`='"+price+"', `Stock`='"+stock+"',`productclassid`='"+idd+"' WHERE `ProductID`='"+id+"';";
            Statement psd = DbUtil.getConnection().createStatement();
            psd.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_productUdateBtnActionPerformed

    private void ShowallBtniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowallBtniActionPerformed
        show_table();

    }//GEN-LAST:event_ShowallBtniActionPerformed

    private void brandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandComboBoxActionPerformed
       
    }//GEN-LAST:event_brandComboBoxActionPerformed

    private void catComboBoxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catComboBoxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catComboBoxiActionPerformed

    private void brandComboBoxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandComboBoxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandComboBoxiActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        int sm=0,lm=0;
        int count=0;
        String pt,pt1 = null,ptb;
        pt=sProductComboBox.getSelectedItem().toString();
        ptb=nameTxtBox.getText();
        //sm=Integer.parseInt(smallintTxtBox.getText());
       // lm=Integer.parseInt(biggerIntTxtBox.getText());
      
            if(pt.equals("Name")){
                pt1="Productname";
            }
            if(pt.equals("Brand")){
                pt1="Brand";
            }
            if(sm==0 && lm==0){
                sm=0;
                lm=100000;
            }
              try {
                  
            String sql = "SELECT * FROM hamroshoestore.productinfo inner join productclass where productinfo.productclassid=productclass.id and "+pt1+"='"+ptb+"';";
            PreparedStatement psd =DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            DefaultTableModel tablemodel =(DefaultTableModel) Ptables.getModel();
            tablemodel.setRowCount(0);

            while(rs.next()){
                tablemodel.addRow(new Object[]{rs.getString("ProductId"),rs.getString("productname"),rs.getString("Brand"),rs.getString("price"),rs.getString("Stock"),rs.getString("productclass")});
            }

           
//            String sql = "SELECT * FROM hamroshoestore.productinfo inner join productclass where productinfo.productclassid=productclass.id and "+pt1+"='"+ptb+" and price between 0 and 2000;";
//            PreparedStatement psd =DbUtil.getConnection().prepareStatement(sql);
//            ResultSet rs = psd.executeQuery();
//            DefaultTableModel tablemodel =(DefaultTableModel) Ptables.getModel();
//            tablemodel.setRowCount(0);

//            while(rs.next()){
//                tablemodel.addRow(new Object[]{rs.getString("ProductId"),rs.getString("productname"),rs.getString("Brand"),rs.getString("price"),rs.getString("Stock"),rs.getString("productclass")});
//            }
            
        }catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void ShowallBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowallBtn1ActionPerformed
        // TODO add your handling code here:
        show_table();
    }//GEN-LAST:event_ShowallBtn1ActionPerformed
 private void show_table() {
            List <dto> list = new doa().productlistinner();
            DefaultTableModel tableModel =(DefaultTableModel) Ptablei.getModel();
            DefaultTableModel tableModels =(DefaultTableModel) Ptables.getModel();
            DefaultTableModel tableModelu =(DefaultTableModel) Ptableu.getModel();
            DefaultTableModel tableModeld =(DefaultTableModel) Ptabled.getModel();
            tableModel.setRowCount(0);
            tableModels.setRowCount(0);
            tableModelu.setRowCount(0);
            tableModeld.setRowCount(0);
            list.forEach(new Consumer<dto>() {
                @Override//self generated
                public void accept(dto t) {
                    tableModel.addRow(new Object[]{t.getPrductId(),t.getProductName(),t.getBrand(),t.getPrice(),t.getQuantity(),t.getProductClass()});
                    tableModels.addRow(new Object[]{t.getPrductId(),t.getProductName(),t.getBrand(),t.getPrice(),t.getQuantity(),t.getProductClass()});
                    tableModelu.addRow(new Object[]{t.getPrductId(),t.getProductName(),t.getBrand(),t.getPrice(),t.getQuantity(),t.getProductClass()});
                    tableModeld.addRow(new Object[]{t.getPrductId(),t.getProductName(),t.getBrand(),t.getPrice(),t.getQuantity(),t.getProductClass()});
                }
            });
        //To change body of generated methods, choose To ols | Templates.
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JPanel InsertionPanel;
    private javax.swing.JTextField PriceTxtBoxi;
    private javax.swing.JTextField PriceTxtbox;
    private javax.swing.JTextField ProductIdBoxd;
    private javax.swing.JTextField ProductIdBoxi;
    private javax.swing.JTextField ProductIdTxtbox;
    private javax.swing.JTextField ProductNameTxtBoxi;
    private javax.swing.JTextField ProductnameTxtbox;
    private javax.swing.JTable Ptabled;
    private javax.swing.JTable Ptablei;
    private javax.swing.JTable Ptables;
    private javax.swing.JTable Ptableu;
    private javax.swing.JTextField QuantityTxtBox;
    private javax.swing.JTextField QuantityTxtBoxi;
    private javax.swing.JToggleButton RefreshBtn;
    private javax.swing.JButton ShowallBtn;
    private javax.swing.JButton ShowallBtn1;
    private javax.swing.JButton ShowallBtni;
    private javax.swing.JButton ShowdataBtn;
    private javax.swing.JComboBox<String> brandComboBox;
    private javax.swing.JComboBox<String> brandComboBoxi;
    private javax.swing.JComboBox<String> catComboBox;
    private javax.swing.JComboBox<String> catComboBoxi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField nameTxtBox;
    private javax.swing.JButton productUdateBtn;
    private javax.swing.JPanel productdeletepanel;
    private javax.swing.JTabbedPane productpanel;
    private javax.swing.JPanel productsearchpanel;
    private javax.swing.JComboBox<String> sProductComboBox;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables

    private void brandInsert() {
         try {
            String sql = "SELECT * FROM hamroshoestore.supplierinfo;";
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            while(rs.next()){
                brandComboBox.addItem(rs.getString("brand"));
                brandComboBoxi.addItem(rs.getString("brand"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void classInsert() {
                try {
            String sql = "SELECT * FROM hamroshoestore.productclass;";
            PreparedStatement psd = DbUtil.getConnection().prepareStatement(sql);
            ResultSet rs = psd.executeQuery();
            while(rs.next()){
                catComboBox.addItem(rs.getString("productclass"));
                catComboBoxi.addItem(rs.getString("productclass"));
              
            }
        } catch (SQLException ex) {
            Logger.getLogger(productmain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    private void show_tabled() {
//        List <dto> list = new doa().productlistinner();
//            DefaultTableModel tableModel =(DefaultTableModel) Ptable.getModel();
//            tableModel.setRowCount(0);
//            list.forEach(new Consumer<dto>() {
//                @Override//self generated
//                public void accept(dto t) {
//                    tableModel.addRow(new Object[]{t.getPrductId(),t.getProductName(),t.getBrand(),t.getPrice(),t.getQuantity(),t.getProductClass()});
//                }
//            });
//        
//    }

}



