/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshoestore;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projectshoestore.billing.iNvoice;
import projectshoestore.mainMenu.MainMenuAdmin1;
import projectshoestore.mainMenu.mainMenuCashier;

/**
 *
 * @author saroj_000
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        
        initComponents();
        insertincombobox();
    }
    public String setname(){
      
        return(UserTxtBox1.getText());
    }
            
    public void insertincombobox(){
        CatagoryComboBox.removeAllItems();
        CatagoryComboBox.addItem("Admin");
        CatagoryComboBox.addItem("Cashier");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        CatagoryComboBox = new javax.swing.JComboBox<>();
        UserTxtBox1 = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(139, 180, 90));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("SHOE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 80));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("STORE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, 80));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("HAMRO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 350, 450));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(195, 195, 129));
        jLabel2.setText("Login ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 170, 60));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        LoginBtn.setBackground(new java.awt.Color(204, 255, 204));
        LoginBtn.setForeground(new java.awt.Color(102, 102, 102));
        LoginBtn.setText("LOGIN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        CancelBtn.setBackground(new java.awt.Color(204, 255, 204));
        CancelBtn.setForeground(new java.awt.Color(102, 102, 102));
        CancelBtn.setText("CANCEL");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        CatagoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatagoryComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(CatagoryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 160, -1));

        UserTxtBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        UserTxtBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTxtBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(UserTxtBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 170, 40));

        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        int s=0;
        int a=0;
        String uName,uPassword,uCat;
        uName = UserTxtBox1.getText();
        uPassword=passwordfield.getText();
        uCat =CatagoryComboBox.getSelectedItem().toString();
        if (uCat.equals("Admin")){
             a =1;
        }
        else if(uCat.equals("Cashier")){
             a =2;
             System.out.println("2");
            
        }
            //might occur error keep in mind
        
        try {
            String sql ="SELECT * FROM hamroshoestore.userinfo where username='"+uName+"' and password='"+uPassword+"'and catagory='"+a+"';";
            PreparedStatement psd =DbUtil.getConnection().prepareStatement(sql);
            ResultSet r = psd.executeQuery();
            while(r.next()){
                s++; 
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(s==1 && a==1){
             MainMenuAdmin1 mm = new MainMenuAdmin1();
             mm.setVisible(true);
             dto name = new dto();
                name.setuName(uName);
                
               
            try {
                String sql="INSERT INTO `hamroshoestore`.`activeuser` (`id`, `Username`, `Password`) VALUES ('1', '"+ uName+"', '"+uPassword+"');";
                Statement psd = DbUtil.getConnection().createStatement();
                 psd.executeUpdate(sql);
                } catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
             this.dispose();
             
        }
        else if(s==1 && a==2){
                mainMenuCashier mc = new mainMenuCashier();
                mc.setVisible(true);
                dto name = new dto();
                name.setuName(uName);
                System.out.println(uName);
                dto un = new dto();
                un.setLuser(uName);
                
                
                try {
                String sql="INSERT INTO `hamroshoestore`.`activeuser` (`id`, `Username`, `Password`) VALUES ('1', '"+ uName+"', '"+uPassword+"');";
                Statement psd = DbUtil.getConnection().createStatement();
                 psd.executeUpdate(sql);
                } catch (SQLException ex) {
                Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            }
               this.dispose();
             
        }
        else
            JOptionPane.showMessageDialog(null, "incorrect password or username pls reenter");
       // psd.executeUpdate(sql);
       
        
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void CatagoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatagoryComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CatagoryComboBoxActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordfieldActionPerformed

    private void UserTxtBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTxtBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTxtBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
                
            }
        });
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox<String> CatagoryComboBox;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField UserTxtBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordfield;
    // End of variables declaration//GEN-END:variables
}
